import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Plugin } from 'vite';

const LEGAL_SOURCE_FILES: Record<string, string> = {
  privacy: 'src/pages/legal/PrivacyPolicyLegalPage.tsx',
  terms: 'src/pages/legal/TermsOfUseLegalPage.tsx',
  cookies: 'src/pages/legal/CookiePolicyLegalPage.tsx',
  disclaimer: 'src/pages/legal/DisclaimerLegalPage.tsx',
};

/**
 * §56.5 — Regenerate `src/generated/legal-dates.ts` from `git log -1` per legal page file.
 */
export function legalDatesPlugin(projectRoot: string): Plugin {
  return {
    name: 'apexlyn-legal-dates',
    buildStart() {
      const dates: Record<string, string> = {};
      for (const [key, rel] of Object.entries(LEGAL_SOURCE_FILES)) {
        const fp = path.join(projectRoot, rel);
        let iso = new Date().toISOString().slice(0, 10);
        try {
          if (fs.existsSync(fp)) {
            const relPosix = rel.split(path.sep).join('/');
            const out = execSync(`git log -1 --format=%cs -- "${relPosix}"`, {
              cwd: projectRoot,
              encoding: 'utf8',
              stdio: ['pipe', 'pipe', 'ignore'],
            }).trim();
            if (out) iso = out;
          }
        } catch {
          /* keep default */
        }
        dates[key] = iso;
      }
      const outPath = path.join(projectRoot, 'src/generated/legal-dates.ts');
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      const lines = Object.entries(dates)
        .map(([k, v]) => `  ${k}: '${v}',`)
        .join('\n');
      fs.writeFileSync(
        outPath,
        `/* Auto-generated by vite plugin apexlyn-legal-dates — do not edit */\n` +
          `export const LEGAL_PAGE_LAST_UPDATED_ISO = {\n${lines}\n} as const;\n` +
          `export type LegalPageSlug = keyof typeof LEGAL_PAGE_LAST_UPDATED_ISO;\n`,
      );
    },
  };
}
